version: '3.7'

services:
  web:
    build: .

    command: python manage.py runserver 0.0.0.0:8999

    ports:
      - 8999:8999
    volumes:
      - .:/code
    
  db:
    image: postgres:12
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: 'db'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'

volumes:
  postgres_data:
