version: '3.7'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8999
    ports:
      - 8999:8999
    volumes:
      - .:/code
    
  db:
    image: postgres:13

    environment:
      POSTGRES_DB: 'db'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'

    volumes:
      - ./postgres_data_new:/var/lib/postgresql/data

volumes:
  postgres_data_new:

