# Generated by Django 5.0.2 on 2024-12-29 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_timetable_owner_timetabletask_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='comments',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='timetabletask',
            name='comments',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
