# Generated by Django 5.0.2 on 2024-03-29 13:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('status', models.CharField(default='notdone', max_length=100)),
                ('target_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('due_date', models.DateField(default=django.utils.timezone.now)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('effort_hours', models.FloatField(default=2.0)),
                ('effort_hours_left', models.FloatField(default=2.0)),
                ('status', models.CharField(default='notdone', max_length=100)),
                ('progress', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('notstarted', 'notstarted'), ('inprogress', 'inprogress'), ('complete', 'complete')], default='notstarted', max_length=100)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('notdone', 'notdone'), ('inprogress', 'inprogress'), ('complete', 'complete')], default='notdone', max_length=100)),
                ('date_completed', models.DateTimeField(blank=True, null=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('effort_hours', models.PositiveIntegerField(blank=True, default=2, null=True)),
                ('backlog', models.BooleanField(blank=True, default=False, null=True)),
                ('date_added', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
    ]
