# Generated by Django 5.0.1 on 2024-01-18 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0008_task_sprint'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='effort_hours',
            field=models.PositiveIntegerField(blank=True, default=2, null=True),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='status',
            field=models.CharField(choices=[('notstarted', 'notstarted'), ('inprogress', 'inprogress'), ('complete', 'complete')], default='notstarted', max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('notdone', 'notdone'), ('inprogress', 'inprogress'), ('complete', 'complete')], default='notdone', max_length=100),
        ),
    ]
