# Generated by Django 5.0.1 on 2024-02-18 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0010_alter_task_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
