# Generated by Django 5.0.1 on 2024-02-18 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0011_alter_task_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
