# Generated by Django 5.0.1 on 2024-02-19 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0012_alter_task_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='end_time',
            field=models.TimeField(default='00:00:00'),
            preserve_default=False,
        ),
    ]
