# Generated by Django 5.0.1 on 2024-02-23 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0013_alter_task_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='backlog',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
