# Generated by Django 5.0.1 on 2024-02-23 05:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0014_task_backlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date_added',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
